### ISSUE TITLE
Function and variable named the same

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/item_drop#10]
https://github.com/minetest-mods/item_drop/blob/29df36b2af814cdc7b6be7f1690089bcdfe4741a/init.lua#L108

https://github.com/minetest-mods/item_drop/blob/29df36b2af814cdc7b6be7f1690089bcdfe4741a/init.lua#L114

Don't know if it's bad practice really, but my Atom linter feature pointed it out.

**Comment by HybridDog** [comment]
This is called shadowing.
```Lua
local keys_pressed -- declare local variable
keys_pressed = function(player) -- set this variable to a function
	local keys_pressed -- declare local variable (but the same name as before)
```
It's not a bad practice, but you should avoid making code harder to understand.
This code is easy to understand (imo):
```Lua
local i = 0
while myfunc() do
	for k = 1,9 do
		local i = math.exp(k / 9)
		myotherfunc(i)
		print(i)
	end
	i = i+1
end
print(i)
```
You don't have to think about giving a proper name to each local variable which makes a short program-and-test more convenient.
If you're shadowing variables with long names (e.g. in this issue's case), one of them likely can be renamed to more properly represent what they mean. l did a commit.

**Comment by tacotexmex** [comment]
I see what you mean. From a nubs perspective (me) that recently got into Lua, writing longer proper names helps me follow my own and other peoples' code. So I kind of want to return the favor for the next person coming along trying to learn. :slightly_smiling_face:

**Comment by joenas** [comment]
> ... writing longer proper names helps me follow my own and others' code 

That is generally best practice in most languages!

https://github.com/Olivine-Labs/lua-style-guide/blob/master/README.md#naming-conventions
