### ISSUE TITLE
[patch] Crash with table textures

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/item_drop#15]
I've cleaned the particle code: https://github.com/HybridDog/item_drop/commit/09e032970856a5c6ce36d5d056d7b40f6b35add5
and then fixed a crash I experienced: https://github.com/HybridDog/item_drop/commit/b7031d3049dfefc45055d5270baa718d08adc6a0

**Comment by tacotexmex** [comment]
Good catch HDog
