### ISSUE TITLE
Support on_pickup item definitions

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/item_drop#17]
Let’s look for a new function in item definitions, `on_pickup`, and run that function on every pickup done by item_drop or by hand.

It’d be useful for experience orbs or other ”pseudo items”, opening up new possibilities. What do you think @HybridDog?

**Comment by HybridDog** [comment]
I think it should be added to minetest, not to this mod.
https://github.com/minetest-mods/item_drop/blob/fc89b2d2b4cad17e121bc4d4e84553a929a7f042/init.lua#L96
https://github.com/minetest/minetest/blob/f0dca284b3d4fe266e88f6df8c6e3ad9d1411496/doc/lua_api.txt#L3321-L3330
You't just need to call on_pickup in the on_punch definition in builtin/.
https://github.com/minetest/minetest/blob/f0dca284b3d4fe266e88f6df8c6e3ad9d1411496/builtin/game/item_entity.lua#L216-L227

**Comment by Desour** [comment]
There's already a PR in minetest for this: https://github.com/minetest/minetest/pull/7712

**Comment by tacotexmex** [comment]
Cool, but why not add it to the mod in the meanwhile? PR could take years…

**Comment by HybridDog** [comment]
I think adding this feature is not the purpose of this mod, you can make another mod for it.

**Comment by tacotexmex** [comment]
But this mod would still need to trigger the function of that other mod, no? How else would the game know when to run the on_pickup function?

**Comment by HybridDog** [comment]
on_pickup is called when on_punch is called, this mod and players do it.

**Comment by tacotexmex** [comment]
Ah, now I see, this mod calls on_punch _already_.

So this other mod just needs to register custom on_punch functions for nodes.
