### ISSUE TITLE
Crash when digging unknown node

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/item_drop#19]
Removed the vines mod from a world, which nodes then became unknown. They still contain the node name however, so when digging them item_drop tries to drop such a node which crashes the game.

The `handle_node_drops` needs to be able to handle the case of unknown nodes with known names.

**Comment by HybridDog** [comment]
Here's a fix:
```diff
diff --git a/init.lua b/init.lua
index 5e8ac8d..6d8db5d 100644
--- a/init.lua
+++ b/init.lua
@@ -320,8 +320,9 @@ and not minetest.settings:get_bool("creative_mode") then
                                name = item:get_name()
                        end
 
-                       if name == "" then
-                               -- Sometimes nothing should be dropped
+                       -- Sometimes nothing should be dropped
+                       if name == ""
+                       or not minetest.registered_nodes[name] then
                                count = 0
                        end
```

**Comment by tacotexmex** [comment]
Excellent, thanks HD. This mod is getting quite solid, all thanks to you.

**Comment by HybridDog** [comment]
I'll merge the fix and api functions now.

**Comment by tacotexmex** [comment]
Oh sorry, I misinterpreted and thought you did this already, hence why I closer the issue. Stay awesome HD!
