### ISSUE TITLE
Settings prefix

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/item_drop#2]
To avoid conflicts without other mods, l think the settings should get the "item_drop." prefix. l do this with my mods and it works well https://github.com/HybridDog/sumpf/blob/master/sumpf/settingtypes.txt.
Do you approve adding this prefix?

**Comment by tacotexmex** [comment]
I too am positive to this change for the reason you mention. However, I've tried to write the mod as a drop-in replacement of the original. This would break that. But maybe it's time to let go of the past and build the best possible mod according to best practices, of which this issue highlights one.

I'm for it **but**, and this should go for development of the mod in general, let's create a `development` or `next` branch for these additions or feature branches for larger ones, for the time being.

Your `settingtypes.txt` is one of the few examples I've seen using the `xx.yy_zz` convention whereas all other mods I've seen uses `xx_yy_zz` for setting vars. Who's right? :)

**Comment by HybridDog** [comment]
l think using `modname.setting_name` looks better than `modname_setting_name`.

> This would break that.

The original mod didn't have settings (except that strange item deletion setting) and doesn't work on current minetest.

**Comment by Desour** [comment]
What about `modname:setting`?
