### ISSUE TITLE
Json related error

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/item_drop#21]
Minetest 5.0, mod installed from CDB
~~~
WARNING[Main]: Undeclared global variable "item_drop" accessed at ...\_Games\minetest-5.0-gc64\bin\..\mods\item_drop\init.lua:4
ACTION[Main]: [MOD] Mobs Redo loaded
ERROR[Main]: Failed to parse json data * Line 1, Column 1
ERROR[Main]:   Syntax error: value, object or array expected.
ERROR[Main]: data: ""
~~~

**Comment by HybridDog** [comment]
I doubt that the json error is caused by item_drop. The Undeclared global variable warning should be fixed in the newest version of item_drop.
What output do you get with minetest --info?

**Comment by Fixer-007** [comment]
Can't reproduce that error

**Comment by Fixer-007** [comment]
Wait a second...

**Comment by Fixer-007** [comment]
Seems like it downloads older version of this plugin via ContentDB... aka this one https://github.com/minetest-mods/item_drop/commit/c52ff0ea55357c49976895036748482584f41bd2
