### ISSUE TITLE
Items are not autopicked up

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/item_drop#22]
Minetest 5.0, CDB mod version. 

What happened? It just worked... now I need to manually pick up all of them, tried to change various settings, including mouse_pickup, disabled key pickup, did not help. Mod default settings are somewhat confusing, i was expecting usual magnet and pick up behaviour, but it does not. Do I need PHD for that :(

How to make it work as usual? Aka drop on dig and autopick up?

**Comment by Desour** [comment]
I can confirm.
The reason is that key triggered item pickup defaults to `true`.
https://github.com/minetest-mods/item_drop/blob/532a3cb0d04da17b3e7811058070a5f347068309/init.lua#L42-L44
Picking up with holding the use key works.
See also https://github.com/minetest-mods/item_drop/commit/31bdc51b427d818609656677dab8dd12362038c7#r29969875.
Edit: And disabling `enable_pickup_key` (which is in settingtypes) does not work. It's misspelled.

**Comment by tacotexmex** [comment]
Just made a cdb release. Will look into the rest.

**Comment by tacotexmex** [comment]
@hybriddog You wanna take a look at this. I’m pressed for time.

**Comment by HybridDog** [comment]
Can I remove the legacy settings support (https://github.com/minetest-mods/item_drop/commit/31bdc51b427d818609656677dab8dd12362038c7)?
I think that almost nobody uses the old PilzAdam item_drop because it works only with fairly old minetest versions.

**Comment by tacotexmex** [comment]
I kind of want to but I don't want the disruption. 🤔  Which version does PilzAdam's version crash with?

**Comment by HybridDog** [comment]
It doesn't crash but the dropped items are immediately picked up, so you cannot drop an item by pressing q if I remember correctly. I'm not sure with which version this happens or if it only happens if you also use the [builtin_item](https://github.com/PilzAdam/builtin_item) mod.

**Comment by HybridDog** [comment]
If the old setting should be supported, this could work if enable_pickup_key should default to false:
```lua
local key_triggered = minetest.settings:get_bool("item_drop.enable_pickup_key")
if key_triggered == nil then
	key_triggered = minetest.settings:get_bool("enable_item_pickup_key")
end
```
and this may work if it should default to true:
```lua
local key_triggered = minetest.settings:get_bool("item_drop.enable_pickup_key")
if key_triggered == nil then
	key_triggered = minetest.settings:get_bool("enable_item_pickup_key")
end
key_triggered = key_triggered ~= false
```

**Comment by tacotexmex** [comment]
I always had pickup key setting on by default since from the beginning that was the main feature. Now I don’t really care which one is default, but @fixer-007 seemed to assume it off by default so if you’re in favor of this as well go for it.

**Comment by HybridDog** [comment]
https://github.com/minetest-mods/item_drop/commit/70b33863223743783fa8b8d16204bcfa9ebd58d0 should fix the problem. Please test if it works correctly.

**Comment by HybridDog** [comment]
>  Now I don’t really care which one is default, but @Fixer-007 seemed to assume it off by default so if you’re in favor of this as well go for it.

I'd like as default behaviour to trigger picking only if the key is not pressed, i.e. set pickup_keyinvert to true.
https://github.com/HybridDog/item_drop/commit/c6229d169573a47841e6d92ec7dd68945ce45840#diff-ea5e1506d88860e4e91783e91211be48

**Comment by Fixer-007** [comment]
I want default behavior like in minecraft

**Comment by tacotexmex** [comment]
Both of your positions will likely seem like the same one to casual players. So go ahead HDog.

I wonder how many users mod will experience the mod as ”broken” with this change though (”suddenly it just picks everything up automatically!1”)

**Comment by HybridDog** [comment]
>[…] go ahead […]

https://github.com/minetest-mods/item_drop/commit/5069afa83443ffed2ae980773b09725bd8fb5696

**Comment by tacotexmex** [comment]
Seems legit.

**Comment by Fixer-007** [comment]
Please do another release on CDB

**Comment by tacotexmex** [comment]
> Please do another release on CDB

Done and released.

**Comment by Fixer-007** [comment]
It works! Thank you!
