### ISSUE TITLE
No item drop when digging a node which drops multiple items

### ISSUE THREAD

**Issue by Ginger88895** [minetest-mods/item_drop#25]
For example, digging "default:clay" would drop "default:clay_lump 4" (which means 4 clay lumps), while the enabling this mod drops nothing.

This can be fixed by replacing the "init.lua" with the code in the attachment (rename to "init.lua").
The change is made inside "handle_node_drops" and utilizes ItemStack.
[init.lua.txt](https://github.com/minetest-mods/item_drop/files/3328112/init.lua.txt)

EDIT: I forgot to make "count" and "name" local...

**Comment by HybridDog** [comment]
https://github.com/minetest-mods/item_drop/commit/5611b4d639a0a77cc8a6f32ba0a50622bc3cb749

**Comment by Ginger88895** [comment]
I can confirm that this update fixes the issue about clay; though I am unsure about the other sections of the update nor could I test it...

**Comment by HybridDog** [comment]
I have never seen an item drop which has toolwear or metadata, so I also haven't tested the other changes. I added them nonetheless to be safe.
