### ISSUE TITLE
Spaces or tabs for indentation

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/item_drop#3]
In my opinion tabs are easier readable than two spaces. Can l change it?

**Comment by tacotexmex** [comment]
I've just changed it to spaces but I'm fine with both (doesn't look any different in my editor). Whatever contributors prefer. But you know, [Developers Who Use Spaces Make More Money Than Those Who Use Tabs](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/). 😉

**Comment by HybridDog** [comment]
Ok, to me tab looks like 4 spaces.

**Comment by HybridDog** [comment]
l've changed the indentation.
