### ISSUE TITLE
sound effect volume/discreteness

### ISSUE THREAD

**Issue by tigersharke** [minetest-mods/item_drop#31]
It seems that the sound effect "ploop" is quite a bit too loud as compared to other sounds-- probably ought not be quite as loud as placing a block. It also seems that volume of "overheard" pickups is a bit too loud as one would expect proximity of pickup effect to be the range of the sound, dropping off fairly sharp.  

Perhaps a quieter sample or attenuation or configuration for the sound effect?

There is no sound for drop (q) of items.

Thank you. Love the mod effect on gameplay.

**Comment by tacotexmex** [comment]
> Perhaps a quieter sample or attenuation or configuration for the sound effect?

The setting is called `item_drop.pickup_sound_gain` and defaults to 0.4. 😃 

I can add a drop sound easily as I've already written this in another mod.

**Comment by tigersharke** [comment]
Thank you. Closing this as resolved and now more than a year old.
