### ISSUE TITLE
Pickup sound is too loud

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/item_drop#4]
Unlike Minecraft's gentle pick up sound, item_drop ones are pretty high volume (comparable to other minetest sounds). This is very irritating for headphone users (like me), default should be much quieter, around 0.1 (compared to current 0.4)

**Comment by tacotexmex** [comment]
Is this even for when you pick up a single item? You're probably right and default should change to at least 0.2. In the meanwhile, you may use the `item_drop.pickup_sound_gain` setting. There's a feature to [pick up items one by one coming in](https://github.com/minetest-mods/item_drop/issues/1#issuecomment-327451778), thus reducing the loud overlapping pops.

**Comment by HybridDog** [comment]
l could make items be picked one by one even without zero velocity mode. This may cause items to fall trough the player without being picked if lots of items are falling at once. It'd actually be a bit realistic l think because untrained people can't catch (concentrate on) many balls at once but only one after another (e.g. when playing tennis).

**Comment by Fixer-007** [comment]
This issue is about loud pick up sound only, it is too loud even for 1 item, setting default to 0.1 is optimal IMO.

**Comment by tacotexmex** [comment]
Let's meet at `0.2`. 🙂 
https://github.com/minetest-mods/item_drop/commit/78ef2a50f65270197825fcd9dbe3b231158e6a0b

**Comment by Fixer-007** [comment]
Thank you, headphone users will be happy.

**Comment by tacotexmex** [comment]
No problem. Might look into softening or replacing the sounds with higher quality ones for that same reason.

**Comment by HybridDog** [comment]
l'm using headphones and don't have a problem with loud pickup noises.
In my opinion the sounds are already soft.
They have quite high quality: 160 kb/s, 44.1 kHz

**Comment by tacotexmex** [comment]
I'm thinking it could be about different taste in what audial priority pickups should have in a game. 

> They have quite high quality: 160 kb/s, 44.1 kHz

I mean that the sample itself could be of higher quality. But that's low priority.

**Comment by HybridDog** [comment]
README.md is out of date
