### ISSUE TITLE
New core throwing distance might make some age check methods irrelevant 

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/item_drop#9]
https://github.com/minetest/minetest/pull/6410 got merged. Will probably find itself into .4.17.
> Side effect is the item is now far enough away to avoid auto-pickup, assuming auto pickup range is set to a practical value like a radius of 1 node.

This should make it possible to simplify hindering just-thrown items to be picked up too fast. If it's possible to differ items dropped from player from other items, those just need to be limited from pickup for a very short time.

**Comment by HybridDog** [comment]
Avoiding picking player-dropped items is already simple. Only player-dropped items have the dropped_by field (correct me if l'm wrong) which is currently used to test if picking is delayed.
l doubt many players throw items and pick them afterwards. They just want to get rid of it.
Or they want to throw it to another player. l could make the delay work only for the player who dropped the item.
